project_id = "qywdsohyuigjmclemqgm"

[functions.analyze-document]
verify_jwt = false

[functions.sync-outlook-emails]
verify_jwt = false

[functions.send-sms-ovh]
verify_jwt = false

[functions.parse-exam-results]
verify_jwt = false

[functions.parse-exam-planning]
verify_jwt = false

[functions.resend-confirmations]
verify_jwt = false

[functions.bridge-bank]
verify_jwt = false

[functions.register-formation-continue]
verify_jwt = false

[functions.upload-document-inscription]
verify_jwt = false

[functions.corriger-qrc]
verify_jwt = false

[functions.categorize-justificatif]
verify_jwt = false

[functions.match-justificatif]
verify_jwt = false
