// ===== Exercices "Communes" — Métropole de Lyon (58) et ZUPC (24) =====
// Généré à partir des listes officielles fournies par la formation.
import { ExerciceItem } from "./types";

export const QUIZ_COMMUNES_METROPOLE: ExerciceItem = {
  id: 7020, actif: true,
  titre: "Quiz — Les 58 communes de la Métropole de Lyon",
  sousTitre: "10 questions : cochez les communes appartenant à la Métropole de Lyon",
  questions: [
    {
      id: 1, enonce: "Cochez UNIQUEMENT les communes qui font partie de la Métropole de Lyon (58 communes au total).",
      choix: [
        { lettre: "A", texte: "Albigny-sur-Saône", correct: true },
        { lettre: "B", texte: "Anse" },
        { lettre: "C", texte: "Brignais" },
        { lettre: "D", texte: "Bron", correct: true },
        { lettre: "E", texte: "Cailloux-sur-Fontaines", correct: true },
        { lettre: "F", texte: "Caluire-et-Cuire", correct: true },
        { lettre: "G", texte: "Champagne-au-Mont-d'Or", correct: true },
        { lettre: "H", texte: "Chaponost" },
        { lettre: "I", texte: "Charbonnières-les-Bains", correct: true },
        { lettre: "J", texte: "Villefranche-sur-Saône" },
      ],
    },
    {
      id: 2, enonce: "Cochez UNIQUEMENT les communes qui font partie de la Métropole de Lyon (58 communes au total).",
      choix: [
        { lettre: "A", texte: "Charly", correct: true },
        { lettre: "B", texte: "Chassieu", correct: true },
        { lettre: "C", texte: "Collonges-au-Mont-d'Or", correct: true },
        { lettre: "D", texte: "Communay" },
        { lettre: "E", texte: "Corbas", correct: true },
        { lettre: "F", texte: "Couzon-au-Mont-d'Or", correct: true },
        { lettre: "G", texte: "Craponne", correct: true },
        { lettre: "H", texte: "L'Arbresle" },
        { lettre: "I", texte: "Tarare" },
        { lettre: "J", texte: "Ternay" },
      ],
    },
    {
      id: 3, enonce: "Cochez UNIQUEMENT les communes qui font partie de la Métropole de Lyon (58 communes au total).",
      choix: [
        { lettre: "A", texte: "Colombier-Saugnieu" },
        { lettre: "B", texte: "Curis-au-Mont-d'Or", correct: true },
        { lettre: "C", texte: "Dardilly", correct: true },
        { lettre: "D", texte: "Décines-Charpieu", correct: true },
        { lettre: "E", texte: "Feyzin", correct: true },
        { lettre: "F", texte: "Fleurieu-sur-Saône", correct: true },
        { lettre: "G", texte: "Mornant" },
        { lettre: "H", texte: "Pusignan" },
        { lettre: "I", texte: "Saint-Symphorien-d'Ozon" },
        { lettre: "J", texte: "Écully", correct: true },
      ],
    },
    {
      id: 4, enonce: "Cochez UNIQUEMENT les communes qui font partie de la Métropole de Lyon (58 communes au total).",
      choix: [
        { lettre: "A", texte: "Fontaines-Saint-Martin", correct: true },
        { lettre: "B", texte: "Fontaines-sur-Saône", correct: true },
        { lettre: "C", texte: "Francheville", correct: true },
        { lettre: "D", texte: "Genay", correct: true },
        { lettre: "E", texte: "Givors", correct: true },
        { lettre: "F", texte: "Grigny-sur-Rhône", correct: true },
        { lettre: "G", texte: "Grézieu-la-Varenne" },
        { lettre: "H", texte: "Millery" },
        { lettre: "I", texte: "Sainte-Consorce" },
        { lettre: "J", texte: "Vourles" },
      ],
    },
    {
      id: 5, enonce: "Cochez UNIQUEMENT les communes qui font partie de la Métropole de Lyon (58 communes au total).",
      choix: [
        { lettre: "A", texte: "Chasselay" },
        { lettre: "B", texte: "Civrieux-d'Azergues" },
        { lettre: "C", texte: "Genas" },
        { lettre: "D", texte: "Irigny", correct: true },
        { lettre: "E", texte: "Jonage", correct: true },
        { lettre: "F", texte: "La Mulatière", correct: true },
        { lettre: "G", texte: "La Tour-de-Salvagny", correct: true },
        { lettre: "H", texte: "Limonest", correct: true },
        { lettre: "I", texte: "Lissieu", correct: true },
        { lettre: "J", texte: "Saint-Bonnet-de-Mure" },
      ],
    },
    {
      id: 6, enonce: "Cochez UNIQUEMENT les communes qui font partie de la Métropole de Lyon (58 communes au total).",
      choix: [
        { lettre: "A", texte: "Chaponnay" },
        { lettre: "B", texte: "Lyon", correct: true },
        { lettre: "C", texte: "Marcy-l'Étoile", correct: true },
        { lettre: "D", texte: "Marennes" },
        { lettre: "E", texte: "Meyzieu", correct: true },
        { lettre: "F", texte: "Mions", correct: true },
        { lettre: "G", texte: "Montanay", correct: true },
        { lettre: "H", texte: "Neuville-sur-Saône", correct: true },
        { lettre: "I", texte: "Simandres" },
        { lettre: "J", texte: "Toussieu" },
      ],
    },
    {
      id: 7, enonce: "Cochez UNIQUEMENT les communes qui font partie de la Métropole de Lyon (58 communes au total).",
      choix: [
        { lettre: "A", texte: "Anse" },
        { lettre: "B", texte: "Brignais" },
        { lettre: "C", texte: "Chaponost" },
        { lettre: "D", texte: "Oullins-Pierre-Bénite", correct: true },
        { lettre: "E", texte: "Poleymieux-au-Mont-d'Or", correct: true },
        { lettre: "F", texte: "Quincieux", correct: true },
        { lettre: "G", texte: "Rillieux-la-Pape", correct: true },
        { lettre: "H", texte: "Rochetaillée-sur-Saône", correct: true },
        { lettre: "I", texte: "Saint-Cyr-au-Mont-d'Or", correct: true },
        { lettre: "J", texte: "Villefranche-sur-Saône" },
      ],
    },
    {
      id: 8, enonce: "Cochez UNIQUEMENT les communes qui font partie de la Métropole de Lyon (58 communes au total).",
      choix: [
        { lettre: "A", texte: "Communay" },
        { lettre: "B", texte: "L'Arbresle" },
        { lettre: "C", texte: "Saint-Didier-au-Mont-d'Or", correct: true },
        { lettre: "D", texte: "Saint-Fons", correct: true },
        { lettre: "E", texte: "Saint-Genis-Laval", correct: true },
        { lettre: "F", texte: "Saint-Genis-les-Ollières", correct: true },
        { lettre: "G", texte: "Saint-Germain-au-Mont-d'Or", correct: true },
        { lettre: "H", texte: "Saint-Priest", correct: true },
        { lettre: "I", texte: "Tarare" },
        { lettre: "J", texte: "Ternay" },
      ],
    },
    {
      id: 9, enonce: "Cochez UNIQUEMENT les communes qui font partie de la Métropole de Lyon (58 communes au total).",
      choix: [
        { lettre: "A", texte: "Colombier-Saugnieu" },
        { lettre: "B", texte: "Mornant" },
        { lettre: "C", texte: "Pusignan" },
        { lettre: "D", texte: "Saint-Romain-au-Mont-d'Or", correct: true },
        { lettre: "E", texte: "Saint-Symphorien-d'Ozon" },
        { lettre: "F", texte: "Sainte-Foy-lès-Lyon", correct: true },
        { lettre: "G", texte: "Sathonay-Camp", correct: true },
        { lettre: "H", texte: "Sathonay-Village", correct: true },
        { lettre: "I", texte: "Solaize", correct: true },
        { lettre: "J", texte: "Tassin-la-Demi-Lune", correct: true },
      ],
    },
    {
      id: 10, enonce: "Cochez UNIQUEMENT les communes qui font partie de la Métropole de Lyon (58 communes au total).",
      choix: [
        { lettre: "A", texte: "Grézieu-la-Varenne" },
        { lettre: "B", texte: "Millery" },
        { lettre: "C", texte: "Sainte-Consorce" },
        { lettre: "D", texte: "Vaulx-en-Velin", correct: true },
        { lettre: "E", texte: "Vernaison", correct: true },
        { lettre: "F", texte: "Villeurbanne", correct: true },
        { lettre: "G", texte: "Vourles" },
        { lettre: "H", texte: "Vénissieux", correct: true },
      ],
    },
  ],
};

export const QUIZ_COMMUNES_ZUPC: ExerciceItem = {
  id: 7021, actif: true,
  titre: "Quiz — Les 24 communes de la ZUPC",
  sousTitre: "6 questions : cochez les communes appartenant à la ZUPC de Lyon",
  questions: [
    {
      id: 1, enonce: "Cochez UNIQUEMENT les communes qui font partie de la ZUPC de Lyon (24 communes au total).",
      choix: [
        { lettre: "A", texte: "Albigny-sur-Saône" },
        { lettre: "B", texte: "Aéroport de Lyon-Saint-Exupéry", correct: true },
        { lettre: "C", texte: "Bron", correct: true },
        { lettre: "D", texte: "Cailloux-sur-Fontaines" },
        { lettre: "E", texte: "Caluire-et-Cuire", correct: true },
        { lettre: "F", texte: "Champagne-au-Mont-d'Or", correct: true },
        { lettre: "G", texte: "Charbonnières-les-Bains" },
        { lettre: "H", texte: "Charly" },
      ],
    },
    {
      id: 2, enonce: "Cochez UNIQUEMENT les communes qui font partie de la ZUPC de Lyon (24 communes au total).",
      choix: [
        { lettre: "A", texte: "Chassieu", correct: true },
        { lettre: "B", texte: "Collonges-au-Mont-d'Or", correct: true },
        { lettre: "C", texte: "Corbas" },
        { lettre: "D", texte: "Couzon-au-Mont-d'Or" },
        { lettre: "E", texte: "Craponne" },
        { lettre: "F", texte: "Curis-au-Mont-d'Or" },
        { lettre: "G", texte: "Décines-Charpieu", correct: true },
        { lettre: "H", texte: "Écully", correct: true },
      ],
    },
    {
      id: 3, enonce: "Cochez UNIQUEMENT les communes qui font partie de la ZUPC de Lyon (24 communes au total).",
      choix: [
        { lettre: "A", texte: "Dardilly" },
        { lettre: "B", texte: "Feyzin" },
        { lettre: "C", texte: "Fleurieu-sur-Saône" },
        { lettre: "D", texte: "Fontaines-Saint-Martin" },
        { lettre: "E", texte: "Francheville", correct: true },
        { lettre: "F", texte: "Genas", correct: true },
        { lettre: "G", texte: "La Mulatière", correct: true },
        { lettre: "H", texte: "Lyon", correct: true },
      ],
    },
    {
      id: 4, enonce: "Cochez UNIQUEMENT les communes qui font partie de la ZUPC de Lyon (24 communes au total).",
      choix: [
        { lettre: "A", texte: "Fontaines-sur-Saône" },
        { lettre: "B", texte: "Genay" },
        { lettre: "C", texte: "Givors" },
        { lettre: "D", texte: "Grigny-sur-Rhône" },
        { lettre: "E", texte: "Meyzieu", correct: true },
        { lettre: "F", texte: "Oullins-Pierre-Bénite", correct: true },
        { lettre: "G", texte: "Rillieux-la-Pape", correct: true },
        { lettre: "H", texte: "Saint-Cyr-au-Mont-d'Or", correct: true },
      ],
    },
    {
      id: 5, enonce: "Cochez UNIQUEMENT les communes qui font partie de la ZUPC de Lyon (24 communes au total).",
      choix: [
        { lettre: "A", texte: "Irigny" },
        { lettre: "B", texte: "Jonage" },
        { lettre: "C", texte: "La Tour-de-Salvagny" },
        { lettre: "D", texte: "Limonest" },
        { lettre: "E", texte: "Saint-Didier-au-Mont-d'Or", correct: true },
        { lettre: "F", texte: "Saint-Fons", correct: true },
        { lettre: "G", texte: "Saint-Priest", correct: true },
        { lettre: "H", texte: "Sainte-Foy-lès-Lyon", correct: true },
      ],
    },
    {
      id: 6, enonce: "Cochez UNIQUEMENT les communes qui font partie de la ZUPC de Lyon (24 communes au total).",
      choix: [
        { lettre: "A", texte: "Lissieu" },
        { lettre: "B", texte: "Marcy-l'Étoile" },
        { lettre: "C", texte: "Mions" },
        { lettre: "D", texte: "Montanay" },
        { lettre: "E", texte: "Tassin-la-Demi-Lune", correct: true },
        { lettre: "F", texte: "Vaulx-en-Velin", correct: true },
        { lettre: "G", texte: "Villeurbanne", correct: true },
        { lettre: "H", texte: "Vénissieux", correct: true },
      ],
    },
  ],
};
