import type { Matiere } from "./examens-blancs-data";

// =============================================
// EXAMEN BLANC 1 — TAXI — Réglementation nationale (16 questions)
// =============================================
export const taxi_nationale_eb1: Matiere = {
  id: "reglementation_taxi",
  nom: "F(T) - Réglementation nationale TAXI",
  duree: 30, coefficient: 3, noteEliminatoire: 6, noteSur: 20,
  questions: [
    { id: 1, type: "QRC", enonce: "Développez le sigle TICPE.", reponseQRC: "Taxe Intérieure sur la Consommation des Produits Énergétiques.", reponses_possibles: ["taxe intérieure", "consommation", "produits énergétiques"] },
    { id: 2, type: "QRC", enonce: "Je veux passer mon véhicule professionnel en véhicule personnel pour la journée que dois-je faire ?", reponseQRC: "Bâcher le lumineux. Éteindre le taximètre. Retirer la carte professionnelle.", reponses_possibles: ["bâcher", "lumineux", "éteindre", "taximètre", "retirer", "carte professionnelle"] },
    { id: 3, type: "QRC", enonce: "Lorsqu'un titulaire ne peut exploiter lui-même son autorisation de stationnement, quelles sont les deux possibilités qui s'offrent à lui pour que son entreprise reste active ?", reponseQRC: "La location du véhicule taxi à un conducteur de taxi. L'emploi d'un salarié.", reponses_possibles: ["location", "conducteur de taxi", "emploi", "salarié"] },
    { id: 4, type: "QRC", enonce: "Quelles sont les différentes autorités administratives compétentes pour délivrer une ADS ?", reponseQRC: "Les mairies.", reponses_possibles: ["mairies", "maire"] },
    { id: 5, type: "QCM", enonce: "Dans le cadre d'une cession d'autorisation, la condition tenant à l'exploitation effective et continue est justifiée :", choix: [{ lettre: "A", texte: "par tout autre moyen défini par un arrêté de l'autorité compétente", correct: true }, { lettre: "B", texte: "par la copie de l'autorisation de stationnement" }, { lettre: "C", texte: "par la copie des déclarations de revenus ou d'avis d'imposition", correct: true }, { lettre: "D", texte: "par la copie de la carte grise du véhicule" }] },
    { id: 6, type: "QCM", enonce: "L'autorisation de stationnement délivrée postérieurement à la loi n°2014-1104 du 1er octobre 2014 :", choix: [{ lettre: "A", texte: "a une durée de validité de 5 ans", correct: true }, { lettre: "B", texte: "est cessible dans des conditions fixées par décret" }, { lettre: "C", texte: "est renouvelable dans des conditions fixées par décret", correct: true }, { lettre: "D", texte: "est cessible" }] },
    { id: 7, type: "QCM", enonce: "Quelle autorité est compétente pour délivrer les autorisations de stationnement sur les aéroports ?", choix: [{ lettre: "A", texte: "les présidents de chambres de métiers et de l'artisanat" }, { lettre: "B", texte: "les présidents de chambres de commerce et d'industrie" }, { lettre: "C", texte: "les préfets ou préfet de police dans leur zone de compétences", correct: true }, { lettre: "D", texte: "les maires" }] },
    { id: 8, type: "QCM", enonce: "Depuis l'entrée en vigueur de la loi du 1er octobre 2014, la demande de renouvellement d'une ADS délivrée postérieurement à cette date doit être réalisée :", choix: [{ lettre: "A", texte: "dans les 3 mois précédant l'expiration de l'ADS", correct: true }, { lettre: "B", texte: "dans l'année de l'expiration de l'ADS" }, { lettre: "C", texte: "dans les 6 mois précédant l'expiration de l'ADS" }] },
    { id: 9, type: "QCM", enonce: "Lorsque le client paye la course par carte bleue puis-je appliquer un supplément ?", choix: [{ lettre: "A", texte: "non", correct: true }, { lettre: "B", texte: "oui en accord avec le client" }, { lettre: "C", texte: "oui sous certaines conditions" }, { lettre: "D", texte: "oui" }] },
    { id: 10, type: "QCM", enonce: "Le véhicule taxi :", choix: [{ lettre: "A", texte: "peut être muni d'un terminal de paiement électronique selon la réglementation locale" }, { lettre: "B", texte: "doit être muni d'un terminal de paiement électronique", correct: true }, { lettre: "C", texte: "n'a pas l'obligation d'être muni d'un terminal de paiement électronique" }] },
    { id: 11, type: "QCM", enonce: "Un transport vers l'hôpital ou un cabinet médical non pris en charge par la caisse d'assurance maladie peut être effectué :", choix: [{ lettre: "A", texte: "uniquement par les taxis non conventionnés" }, { lettre: "B", texte: "par tous les taxis", correct: true }, { lettre: "C", texte: "uniquement par les taxis conventionnés" }] },
    { id: 12, type: "QCM", enonce: "Nul ne peut s'inscrire à l'examen en vue de la délivrance du certificat de capacité professionnelle de conducteur de taxi :", choix: [{ lettre: "A", texte: "s'il a fait l'objet dans les 5 ans d'une exclusion pour fraude", correct: true }, { lettre: "B", texte: "s'il a fait l'objet dans les 10 ans d'une exclusion pour fraude" }, { lettre: "C", texte: "s'il a fait l'objet dans les 5 ans d'un retrait définitif de la carte professionnelle", correct: true }] },
    { id: 13, type: "QCM", enonce: "Je veux faire du transport scolaire avec mon véhicule taxi que dois-je faire ?", choix: [{ lettre: "A", texte: "afficher une pancarte transport d'enfants", correct: true }, { lettre: "B", texte: "avoir un accompagnateur", correct: true }, { lettre: "C", texte: "bâcher le lumineux", correct: true }, { lettre: "D", texte: "retirer la carte professionnelle" }] },
    { id: 14, type: "QCM", enonce: "Je mets en circulation un taxi de remplacement, quelle autorité dois-je aviser ?", choix: [{ lettre: "A", texte: "la préfecture, la chambre de métiers, le RSI ou la CPAM et le service des fraudes" }, { lettre: "B", texte: "la préfecture, la mairie de l'ADS remplacée, la CPAM et le service des fraudes" }, { lettre: "C", texte: "la préfecture, la chambre de métiers, la CPAM dans le cas d'un taxi conventionné et le service des fraudes", correct: true }] },
    { id: 15, type: "QCM", enonce: "Quelle est l'autorité compétente pour décider de l'usage de signe distinctif commun à l'ensemble des taxis, notamment une couleur unique ?", choix: [{ lettre: "A", texte: "l'autorité compétente est exclusivement le préfet" }, { lettre: "B", texte: "l'autorité compétente est exclusivement le maire" }, { lettre: "C", texte: "l'autorité compétente est celle qui délivre les autorisations de stationnement", correct: true }] },
    { id: 16, type: "QCM", enonce: "Si le client vous demande une facture vous devez lui fournir :", choix: [{ lettre: "A", texte: "l'original du ticket de l'imprimante et une facture" }, { lettre: "B", texte: "une facture et une copie du ticket de l'imprimante" }, { lettre: "C", texte: "une copie du ticket de l'imprimante" }, { lettre: "D", texte: "l'original du ticket de l'imprimante", correct: true }] },
  ]
};

// =============================================
// EXAMEN BLANC 1 — TAXI — Réglementation locale (8 questions)
// =============================================
export const taxi_locale_eb1: Matiere = {
  id: "reglementation_taxi2",
  nom: "G(T) - Connaissance du territoire et réglementation locale TAXI",
  duree: 20, coefficient: 3, noteEliminatoire: 6, noteSur: 20,
  questions: [
    { id: 1, type: "QRC", enonce: "Citez 4 stations de TAXI du 6ème arrondissement de Lyon.", reponseQRC: "Station Cours Vitton. Angle rue Masséna. Place du Général Leclerc. Entrée du parc de la Tête d'Or. Avenue du Général Brosset (Métro Brotteaux). Place du Maréchal Lyautey (Métro Foch).", reponses_possibles: ["Cours Vitton", "Général Leclerc", "Tête d'Or", "Brotteaux", "Maréchal Lyautey", "Masséna"] },
    { id: 2, type: "QRC", enonce: "Citez 4 mentions qui doivent être inscrites sur l'affichette TAXIS.", reponseQRC: "Les taux horaires et kilométriques. Les montants et conditions de la prise en charge et des suppléments. Les conditions de délivrance d'une note. L'information que le consommateur peut régler par carte bancaire. L'adresse de réclamation.", reponses_possibles: ["taux horaires", "kilométriques", "prise en charge", "suppléments", "carte bancaire", "réclamation"] },
    { id: 3, type: "QCM", enonce: "Que signifie le tarif A ?", choix: [{ lettre: "A", texte: "Course de jour" }, { lettre: "B", texte: "Trajet aller avec le client et retour en charge à la station" }, { lettre: "C", texte: "Course de nuit, dimanche et jours fériés ou route enneigée/verglacée" }, { lettre: "D", texte: "Trajet aller avec le client et retour à vide à la station", correct: true }] },
    { id: 4, type: "QCM", enonce: "Quel est le montant du supplément par passager ?", choix: [{ lettre: "A", texte: "2 €" }, { lettre: "B", texte: "2.50 €" }, { lettre: "C", texte: "4 €", correct: true }, { lettre: "D", texte: "3 €" }] },
    { id: 5, type: "QCM", enonce: "Le supplément bagage est pour :", choix: [{ lettre: "A", texte: "Les valises au-delà de trois" }, { lettre: "B", texte: "Les valises au-delà de quatre" }, { lettre: "C", texte: "Les valises au-delà de cinq", correct: true }] },
    { id: 6, type: "QCM", enonce: "Où se situe le musée LUGDUNUM ?", choix: [{ lettre: "A", texte: "46 allées d'Italie 69005" }, { lettre: "B", texte: "2 rue Bichat 69005" }, { lettre: "C", texte: "63 rue Philippe de Lassalle 69005" }, { lettre: "D", texte: "17 rue Cléberg 69005", correct: true }] },
    { id: 7, type: "QCM", enonce: "Quel est le prix au km du tarif C ?", choix: [{ lettre: "A", texte: "2,31€" }, { lettre: "B", texte: "2€", correct: true }, { lettre: "C", texte: "2,28€" }, { lettre: "D", texte: "2,50€" }] },
    { id: 8, type: "QCM", enonce: "Où se situe la mairie de Villeurbanne ?", choix: [{ lettre: "A", texte: "5 place du Petit Collège 69100" }, { lettre: "B", texte: "6 place du Marché 69100" }, { lettre: "C", texte: "16 place Jean Macé 69100" }, { lettre: "D", texte: "place du Dr Lazarre Goujon 69100", correct: true }] },
  ]
};

// =============================================
// EXAMEN BLANC 2 — TAXI — Réglementation nationale (16 questions)
// =============================================
export const taxi_nationale_eb2: Matiere = {
  id: "reglementation_taxi",
  nom: "F(T) - Réglementation nationale TAXI",
  duree: 30, coefficient: 3, noteEliminatoire: 6, noteSur: 20,
  questions: [
    { id: 1, type: "QRC", enonce: "Citez un cas pour lequel l'ADS est retirée définitivement.", reponseQRC: "Après retrait définitif de la carte professionnelle. À la demande du titulaire. En cas d'inaptitude définitive entraînant l'annulation du permis de conduire. En cas de décès du titulaire. L'autorisation n'est pas exploitée de façon effective et continue. Violation grave et répétée de la réglementation.", reponses_possibles: ["retrait définitif", "carte professionnelle", "inaptitude", "annulation permis", "décès", "violation grave"] },
    { id: 2, type: "QRC", enonce: "Citez 2 autres sanctions possibles en cas de délit (15 000 € d'amende et un an d'emprisonnement).", reponseQRC: "La suspension, pour une durée de 5 ans au plus, du permis de conduire. L'immobilisation, pour une durée d'un an maximum, du véhicule. La confiscation du véhicule.", reponses_possibles: ["suspension", "permis", "immobilisation", "confiscation", "véhicule"] },
    { id: 3, type: "QRC", enonce: "Que signifie la TICPE ?", reponseQRC: "Taxe Intérieure de Consommation sur les Produits Énergétiques.", reponses_possibles: ["taxe intérieure", "consommation", "produits énergétiques"] },
    { id: 4, type: "QRC", enonce: "Citez 3 mentions devant être inscrites sur le bon de commande des taxis.", reponseQRC: "Nom ou dénomination sociale et coordonnées de la société. Numéro SIREN/SIRET. Nom et coordonnées téléphoniques du client. Date et heure de la réservation. Date et heure de la prise en charge souhaitée. Lieu de prise en charge.", reponses_possibles: ["dénomination sociale", "SIREN", "SIRET", "coordonnées", "client", "réservation", "prise en charge"] },
    { id: 5, type: "QRC", enonce: "Définir le TAXI.", reponseQRC: "Les taxis sont des véhicules automobiles comportant, outre le siège du conducteur, huit places assises au maximum, munis d'équipements spéciaux et d'un terminal de paiement électronique, dont le propriétaire ou l'exploitant est titulaire d'une autorisation de stationnement sur la voie publique, en attente de la clientèle, afin d'effectuer à titre onéreux le transport particulier des personnes et de leurs bagages.", reponses_possibles: ["huit places", "équipements spéciaux", "terminal de paiement", "autorisation de stationnement", "voie publique", "titre onéreux"] },
    { id: 6, type: "QCM", enonce: "Chaque intervention sur les équipements spéciaux des taxis doit être consignée sur un carnet spécifique, comment s'appelle ce document ?", choix: [{ lettre: "A", texte: "Carnet d'entretien du véhicule" }, { lettre: "B", texte: "Carnet d'intervention spécifique" }, { lettre: "C", texte: "Carnet métrologique", correct: true }] },
    { id: 7, type: "QCM", enonce: "Que signifie CPAM ?", choix: [{ lettre: "A", texte: "Caisse primaire d'assurance maternité" }, { lettre: "B", texte: "Caisse primaire d'assurance maladie", correct: true }, { lettre: "C", texte: "Caisse principe d'assurance maladie" }, { lettre: "D", texte: "Caisse primordiale d'assurance maternité" }] },
    { id: 8, type: "QCM", enonce: "Quelle sanction risque-t-on en cas d'absence de taximètre conforme ?", choix: [{ lettre: "A", texte: "3ème classe", correct: true }, { lettre: "B", texte: "2ème classe" }, { lettre: "C", texte: "1ère classe" }] },
    { id: 9, type: "QCM", enonce: "L'activité de taxi fait partie :", choix: [{ lettre: "A", texte: "Du transport public collectif de personnes" }, { lettre: "B", texte: "Du transport public particulier de personnes", correct: true }, { lettre: "C", texte: "Du transport privé de personnes" }] },
    { id: 10, type: "QCM", enonce: "Quelle sanction risque-t-on en cas d'absence d'imprimante connectée au taximètre ?", choix: [{ lettre: "A", texte: "3ème classe", correct: true }, { lettre: "B", texte: "2ème classe" }, { lettre: "C", texte: "1ère classe" }] },
    { id: 11, type: "QCM", enonce: "Quel statut permet d'exploiter l'autorisation de stationnement de la société ?", choix: [{ lettre: "A", texte: "Taxi Salarié", correct: true }, { lettre: "B", texte: "Taxi Coopérateur", correct: true }, { lettre: "C", texte: "Taxi Gérant" }] },
    { id: 12, type: "QCM", enonce: "Quelle sanction risque-t-on en cas d'exercice illégal de l'activité : absence d'autorisation de stationnement ?", choix: [{ lettre: "A", texte: "3ème classe" }, { lettre: "B", texte: "5ème classe" }, { lettre: "C", texte: "Délit", correct: true }] },
    { id: 13, type: "QCM", enonce: "Quels éléments ne figurent pas sur le recto de la carte TAXI ?", choix: [{ lettre: "A", texte: "le code à barres bidimensionnel et la mention « 2D-DOC »" }, { lettre: "B", texte: "le prénom du conducteur", correct: true }, { lettre: "C", texte: "le numéro de la carte" }, { lettre: "D", texte: "la signature du conducteur", correct: true }] },
    { id: 14, type: "QCM", enonce: "Par qui sont gérées et entretenues les stations de TAXI ?", choix: [{ lettre: "A", texte: "La mairie", correct: true }, { lettre: "B", texte: "La préfecture" }, { lettre: "C", texte: "La métropole" }] },
    { id: 15, type: "QCM", enonce: "Je peux revendre (hors cas dérogatoires) ma licence si je l'ai achetée au bout de :", choix: [{ lettre: "A", texte: "5 ans", correct: true }, { lettre: "B", texte: "1 an" }, { lettre: "C", texte: "3 ans" }] },
    { id: 16, type: "QCM", enonce: "Quels types de transports collectifs puis-je effectuer en tant que taxi si je suis inscrit à la DREAL ?", choix: [{ lettre: "A", texte: "Services réguliers" }, { lettre: "B", texte: "Services occasionnels", correct: true }, { lettre: "C", texte: "Services à la demande", correct: true }] },
  ]
};

// =============================================
// EXAMEN BLANC 2 — TAXI — Réglementation locale (8 questions)
// =============================================
export const taxi_locale_eb2: Matiere = {
  id: "reglementation_taxi2",
  nom: "G(T) - Connaissance du territoire et réglementation locale TAXI",
  duree: 20, coefficient: 3, noteEliminatoire: 6, noteSur: 20,
  questions: [
    { id: 1, type: "QRC", enonce: "Citez 4 consulats sur Lyon 6.", reponseQRC: "Consulat du Portugal (71 rue Crillon). Consulat d'Allemagne (33 bd des Belges). Consulat d'Algérie (126 rue Vauban). Consulat de Chine (69 rue Duquesne). Consulat de Côte d'Ivoire (5 av Maréchal Foch). Consulat de Malte (15 place Jules Ferry). Consulat du Sénégal (97 rue Garibaldi). Consulat d'Italie (5 rue du Commandant Faurax). Consulat de Pologne (79 rue Crillon). Consulat de Turquie (87 rue de Sèze).", reponses_possibles: ["Portugal", "Allemagne", "Algérie", "Chine", "Côte d'Ivoire", "Malte", "Sénégal", "Italie", "Pologne", "Turquie"] },
    { id: 2, type: "QRC", enonce: "Citez 4 adresses de mairie sur Lyon.", reponseQRC: "Lyon 1 : 2 place Sathonay. Lyon 2 : 2 rue d'Enghien. Lyon 3 : 18 rue François Garcin. Lyon 4 : 133 boulevard de la Croix Rousse. Lyon 5 : 14 rue Dr Edmond Locard. Lyon 6 : 58 rue de Sèze. Lyon 7 : 16 place Jean Macé. Lyon 8 : 12 avenue Jean Mermoz. Lyon 9 : 6 place du Marché.", reponses_possibles: ["Sathonay", "Enghien", "Garcin", "Croix Rousse", "Locard", "Sèze", "Jean Macé", "Mermoz", "Marché"] },
    { id: 3, type: "QCM", enonce: "Que signifie le tarif B ?", choix: [{ lettre: "A", texte: "Course de jour" }, { lettre: "B", texte: "Trajet aller avec le client et retour en charge à la station" }, { lettre: "C", texte: "Course de nuit, dimanche et jours fériés ou route enneigée/verglacée" }, { lettre: "D", texte: "Trajet aller avec le client et retour à vide à la station", correct: true }] },
    { id: 4, type: "QCM", enonce: "Quel est le montant de la réservation immédiate ?", choix: [{ lettre: "A", texte: "2 €" }, { lettre: "B", texte: "2.50 €" }, { lettre: "C", texte: "4 €", correct: true }, { lettre: "D", texte: "3 €" }] },
    { id: 5, type: "QCM", enonce: "Quel est le montant de la réservation à l'avance ?", choix: [{ lettre: "A", texte: "2 €", correct: true }, { lettre: "B", texte: "2.50 €" }, { lettre: "C", texte: "4 €" }, { lettre: "D", texte: "3 €" }] },
    { id: 6, type: "QCM", enonce: "La basilique de Notre-Dame de Fourvière est-elle inscrite au patrimoine mondial de l'UNESCO ?", choix: [{ lettre: "A", texte: "oui", correct: true }, { lettre: "B", texte: "non" }] },
    { id: 7, type: "QCM", enonce: "Quel est le prix au km du tarif B ?", choix: [{ lettre: "A", texte: "2,31 €" }, { lettre: "B", texte: "1,54 €", correct: true }, { lettre: "C", texte: "1,50 €" }] },
    { id: 8, type: "QCM", enonce: "Où se situe le consulat du Japon ?", choix: [{ lettre: "A", texte: "2/4 rue Carry 69003" }, { lettre: "B", texte: "131 Boulevard de Stalingrad, 69100", correct: true }, { lettre: "C", texte: "126 rue Vauban 69006" }, { lettre: "D", texte: "26 Rue Louis Blanc 69006" }] },
  ]
};

// =============================================
// EXAMEN BLANC 3 — TAXI — Réglementation nationale (16 questions)
// =============================================
export const taxi_nationale_eb3: Matiere = {
  id: "reglementation_taxi",
  nom: "F(T) - Réglementation nationale TAXI",
  duree: 30, coefficient: 3, noteEliminatoire: 6, noteSur: 20,
  questions: [
    { id: 1, type: "QRC", enonce: "Je veux passer mon véhicule professionnel en véhicule personnel pour la journée que dois-je faire ?", reponseQRC: "Bâcher le lumineux. Éteindre le taximètre. Retirer la carte professionnelle.", reponses_possibles: ["bâcher", "lumineux", "éteindre", "taximètre", "retirer", "carte professionnelle"] },
    { id: 2, type: "QRC", enonce: "Quelle est la sanction encourue pour l'exercice de l'activité de conducteur de taxi sans être titulaire de la carte professionnelle en cours de validité ?", reponseQRC: "Contravention de 5ème classe : 1 500 euros d'amende.", reponses_possibles: ["5ème classe", "1500", "amende"] },
    { id: 3, type: "QRC", enonce: "Quelles sont les conditions de stationnement des taxis en attente de la clientèle ?", reponseQRC: "Le conducteur de taxi ne peut stationner en attente de la clientèle que dans sa zone de prise en charge et seulement dans des stations aménagées, sauf s'il est réservé ou retenu hors de sa zone. Le dispositif lumineux ne doit pas être recouvert.", reponses_possibles: ["zone de prise en charge", "stations aménagées", "lumineux", "réservé"] },
    { id: 4, type: "QRC", enonce: "Développez le sigle TICPE.", reponseQRC: "Taxe Intérieure sur la Consommation des Produits Énergétiques.", reponses_possibles: ["taxe intérieure", "consommation", "produits énergétiques"] },
    { id: 5, type: "QCM", enonce: "Est-il possible pendant une course de changer le tarif au taximètre et à quelle condition ?", choix: [{ lettre: "A", texte: "oui, sans condition" }, { lettre: "B", texte: "oui, au changement d'heure (jour/nuit) en prévenant le client", correct: true }, { lettre: "C", texte: "non, jamais" }, { lettre: "D", texte: "oui, à la demande du client" }] },
    { id: 6, type: "QCM", enonce: "Qui décide du montant de la taxe de stationnement ?", choix: [{ lettre: "A", texte: "la préfecture" }, { lettre: "B", texte: "le maire et son conseil municipal", correct: true }, { lettre: "C", texte: "le trésor public" }, { lettre: "D", texte: "le ministère de l'économie" }] },
    { id: 7, type: "QCM", enonce: "Un conducteur de taxi peut-il prendre en charge un client dans une commune autre que celle dans laquelle il exploite l'ADS ?", choix: [{ lettre: "A", texte: "non, en aucun cas" }, { lettre: "B", texte: "oui, s'il demeure dans cette commune" }, { lettre: "C", texte: "oui, s'il a fait l'objet d'une réservation préalable", correct: true }] },
    { id: 8, type: "QCM", enonce: "Si le client vous demande une facture vous devez lui fournir :", choix: [{ lettre: "A", texte: "l'original du ticket de l'imprimante", correct: true }, { lettre: "B", texte: "une copie du ticket de l'imprimante" }, { lettre: "C", texte: "une facture et une copie du ticket de l'imprimante" }] },
    { id: 9, type: "QCM", enonce: "Où doit-on adresser une demande de détaxe de carburants ?", choix: [{ lettre: "A", texte: "au bureau des taxis de la Préfecture" }, { lettre: "B", texte: "à la Direction Départementale des Territoires et de la Mer" }, { lettre: "C", texte: "à la Direction des Douanes", correct: true }] },
    { id: 10, type: "QCM", enonce: "À quelle périodicité un conducteur de taxi doit-il renouveler sa demande d'inscription sur la liste d'attente en vue de l'obtention d'une licence gratuite ?", choix: [{ lettre: "A", texte: "c'est automatique" }, { lettre: "B", texte: "tous les ans", correct: true }, { lettre: "C", texte: "tous les 2 ans" }] },
    { id: 11, type: "QCM", enonce: "Chaque intervention sur les équipements spéciaux des taxis doit être consignée sur un carnet spécifique : comment s'appelle ce document ?", choix: [{ lettre: "A", texte: "carnet d'entretien du véhicule" }, { lettre: "B", texte: "carnet d'intervention spécifique" }, { lettre: "C", texte: "carnet métrologique", correct: true }] },
    { id: 12, type: "QCM", enonce: "Le véhicule taxi doit être muni d'une plaque :", choix: [{ lettre: "A", texte: "visible de l'extérieur", correct: true }, { lettre: "B", texte: "indiquant le numéro de l'autorisation de stationnement", correct: true }, { lettre: "C", texte: "indiquant le nom du propriétaire de l'ADS" }, { lettre: "D", texte: "indiquant l'adresse de la préfecture" }] },
    { id: 13, type: "QCM", enonce: "Quelles sont les composantes des tarifs des courses de taxi ?", choix: [{ lettre: "A", texte: "prise en charge, indemnité kilométrique, heure d'attente ou marche lente", correct: true }, { lettre: "B", texte: "indemnité horaire, prise en charge, marche lente" }, { lettre: "C", texte: "indemnité horaire, indemnité kilométrique, heure d'attente" }] },
    { id: 14, type: "QCM", enonce: "En cas de changement de tarif, sous quel délai le chauffeur doit-il modifier son compteur ?", choix: [{ lettre: "A", texte: "1 mois" }, { lettre: "B", texte: "2 mois", correct: true }, { lettre: "C", texte: "3 mois" }] },
    { id: 15, type: "QCM", enonce: "Quel est l'emplacement du taximètre ?", choix: [{ lettre: "A", texte: "installé à l'intérieur du véhicule, sur le pare-brise arrière côté droit" }, { lettre: "B", texte: "installé sur le toit à l'extérieur du véhicule" }, { lettre: "C", texte: "installé à l'intérieur avant du véhicule, à la portée du conducteur et visible des clients", correct: true }, { lettre: "D", texte: "installé à l'intérieur du véhicule, sur l'aile droite" }] },
    { id: 16, type: "QCM", enonce: "Par quel texte réglementaire national sont modifiés les tarifs des courses de taxi ?", choix: [{ lettre: "A", texte: "un arrêté", correct: true }, { lettre: "B", texte: "un décret" }, { lettre: "C", texte: "une loi" }] },
  ]
};

// =============================================
// EXAMEN BLANC 3 — TAXI — Réglementation locale (8 questions)
// =============================================
export const taxi_locale_eb3: Matiere = {
  id: "reglementation_taxi2",
  nom: "G(T) - Connaissance du territoire et réglementation locale TAXI",
  duree: 20, coefficient: 3, noteEliminatoire: 6, noteSur: 20,
  questions: [
    { id: 1, type: "QRC", enonce: "Citez 4 musées de Lyon.", reponseQRC: "Musée des Beaux-Arts (20 place des Terreaux 69001). Musée des Confluences (86 quai Perrache 69002). Musée de l'Imprimerie (13 rue de la Poulaillerie 69002). Maison des Canuts (10 rue d'Ivry 69004). Musée Lugdunum (17 rue Cléberg 69005). Musée d'Art Contemporain (81 quai Charles de Gaulle 69006). Institut Lumière (25 rue du 1er Film 69008).", reponses_possibles: ["Beaux-Arts", "Confluences", "Imprimerie", "Canuts", "Lugdunum", "Art Contemporain", "Lumière", "Résistance", "Déportation"] },
    { id: 2, type: "QRC", enonce: "Citez 4 hôpitaux à Bron.", reponseQRC: "Hôpital Femme-Mère-Enfant (59 Bd Pinel). Hôpital Pierre Wertheimer - neurologique (59 Bd Pinel). Hôpital cardiovasculaire et pneumologique Louis Pradel (59 Bd Pinel). Centre Hospitalier Le Vinatier (95 Bd Pinel).", reponses_possibles: ["Femme-Mère-Enfant", "Wertheimer", "Louis Pradel", "Vinatier", "Pinel"] },
    { id: 3, type: "QCM", enonce: "Que signifie le tarif D ?", choix: [{ lettre: "A", texte: "Course de jour" }, { lettre: "B", texte: "Trajet aller avec le client et retour en charge à la station" }, { lettre: "C", texte: "Course de nuit, dimanche et jours fériés ou route enneigée/verglacée" }, { lettre: "D", texte: "Trajet aller avec le client et retour à vide à la station", correct: true }] },
    { id: 4, type: "QCM", enonce: "Quel est le tarif maximum de prise en charge sur le département du Rhône par horaire ?", choix: [{ lettre: "A", texte: "35,20 €" }, { lettre: "B", texte: "35,25 €" }, { lettre: "C", texte: "35,30 €", correct: true }, { lettre: "D", texte: "40,40 €" }] },
    { id: 5, type: "QCM", enonce: "Quelle(s) commune(s) ne fait (font) pas partie de la ZUPC ?", choix: [{ lettre: "A", texte: "Caluire-et-Cuire" }, { lettre: "B", texte: "Saint-Priest" }, { lettre: "C", texte: "Chassieu" }, { lettre: "D", texte: "Villefranche", correct: true }] },
    { id: 6, type: "QCM", enonce: "Quel est le prix au km du tarif D ?", choix: [{ lettre: "A", texte: "2,43 €" }, { lettre: "B", texte: "1,54 €" }, { lettre: "C", texte: "1,22 €", correct: true }] },
    { id: 7, type: "QCM", enonce: "Où se situe la chambre régionale d'agriculture ?", choix: [{ lettre: "A", texte: "2/4 rue Carry" }, { lettre: "B", texte: "23 rue Jean Baldassini", correct: true }, { lettre: "C", texte: "126 rue Vauban" }, { lettre: "D", texte: "26 rue Duquesne" }] },
    { id: 8, type: "QCM", enonce: "Qui est le maire de la ville de Lyon ?", choix: [{ lettre: "A", texte: "François Marchal" }, { lettre: "B", texte: "Julien Victoire" }, { lettre: "C", texte: "Jean François Debat" }, { lettre: "D", texte: "Grégory Doucet", correct: true }] },
  ]
};

// =============================================
// EXAMEN BLANC 4 — TAXI — Réglementation nationale (16 questions)
// =============================================
export const taxi_nationale_eb4: Matiere = {
  id: "reglementation_taxi",
  nom: "F(T) - Réglementation nationale TAXI",
  duree: 30, coefficient: 3, noteEliminatoire: 6, noteSur: 20,
  questions: [
    { id: 1, type: "QRC", enonce: "Lorsqu'un titulaire ne peut exploiter lui-même son autorisation de stationnement, quelles sont les deux possibilités qui s'offrent à lui pour que son entreprise reste active ?", reponseQRC: "La location du véhicule taxi à un conducteur de taxi (location-gérance). L'emploi d'un salarié.", reponses_possibles: ["location", "conducteur de taxi", "location-gérance", "emploi", "salarié"] },
    { id: 2, type: "QRC", enonce: "Citez 4 équipements obligatoires hors taximètre, lumineux, plaques scellées et imprimante.", reponseQRC: "Terminal de paiement électronique. Carnet de métrologie. Les tarifs affichés. La trousse à pharmacie. Un facturier.", reponses_possibles: ["terminal de paiement", "carnet de métrologie", "tarifs", "trousse à pharmacie", "facturier"] },
    { id: 3, type: "QRC", enonce: "Quelles sont les sanctions administratives encourues par un titulaire d'une ADS en cas de violation de la réglementation ?", reponseQRC: "L'avertissement. Le retrait temporaire ou définitif de l'ADS.", reponses_possibles: ["avertissement", "retrait", "temporaire", "définitif", "ADS"] },
    { id: 4, type: "QRC", enonce: "Citez les 2 types de trajet ouvrant droit au remboursement d'une fraction de la TICPE.", reponseQRC: "Exercice de la profession (trajet professionnel). Aller-retour quotidien domicile – lieu de travail.", reponses_possibles: ["professionnel", "profession", "domicile", "travail", "aller-retour"] },
    { id: 5, type: "QCM", enonce: "Où doit être apposée la carte professionnelle d'un conducteur de taxi ?", choix: [{ lettre: "A", texte: "sur le pare-brise avant côté passager" }, { lettre: "B", texte: "dans le véhicule, tant qu'elle est lisible du siège arrière" }, { lettre: "C", texte: "sur le pare-brise avant côté conducteur", correct: true }] },
    { id: 6, type: "QCM", enonce: "Lors de la cession d'une ADS, quel document permet au vendeur de justifier qu'elle a été exploitée de manière effective et continue ?", choix: [{ lettre: "A", texte: "Un certificat médical délivré par un médecin agréé" }, { lettre: "B", texte: "La carte grise du véhicule" }, { lettre: "C", texte: "Bilan comptable, fiches de paie", correct: true }] },
    { id: 7, type: "QCM", enonce: "Le véhicule taxi doit être muni d'une plaque :", choix: [{ lettre: "A", texte: "indiquant le nom du propriétaire de l'ADS" }, { lettre: "B", texte: "visible de l'extérieur", correct: true }, { lettre: "C", texte: "indiquant l'adresse de la préfecture" }, { lettre: "D", texte: "indiquant le numéro de l'autorisation de stationnement", correct: true }] },
    { id: 8, type: "QCM", enonce: "Les autorisations de stationnement délivrées depuis la loi du 1er octobre 2014 :", choix: [{ lettre: "A", texte: "Peuvent être exploitées par des sociétaires de coopératives" }, { lettre: "B", texte: "Doivent être exploitées personnellement", correct: true }, { lettre: "C", texte: "Peuvent être exploitées par des salariés" }, { lettre: "D", texte: "Peuvent être exploitées par des locataires-gérants" }] },
    { id: 9, type: "QCM", enonce: "Un compteur horokilométrique permet :", choix: [{ lettre: "A", texte: "De calculer le montant de la course", correct: true }, { lettre: "B", texte: "D'afficher la durée de la course" }, { lettre: "C", texte: "D'afficher le nombre de kilomètres parcourus" }] },
    { id: 10, type: "QCM", enonce: "Le véhicule taxi doit être muni d'un terminal de paiement électronique :", choix: [{ lettre: "A", texte: "Si le préfet du département le prévoit par arrêté" }, { lettre: "B", texte: "Obligatoirement dans tous les cas" }, { lettre: "C", texte: "Seulement dans les grandes villes" }] },
    { id: 11, type: "QCM", enonce: "Le registre de disponibilité des taxis fait l'objet d'un enregistrement d'informations relatives aux ADS lors :", choix: [{ lettre: "A", texte: "des changements des équipements spéciaux" }, { lettre: "B", texte: "des renouvellements et des ventes d'ADS", correct: true }, { lettre: "C", texte: "des formations quinquennales obligatoires" }, { lettre: "D", texte: "des délivrances et des retraits d'ADS", correct: true }] },
    { id: 12, type: "QCM", enonce: "Le conducteur de taxi a le droit :", choix: [{ lettre: "A", texte: "de ne pas attendre les voyageurs s'ils se trouvent dans une voie où le stationnement est impossible", correct: true }, { lettre: "B", texte: "d'être accompagné de personnes autres que des clients" }, { lettre: "C", texte: "de solliciter un pourboire" }] },
    { id: 13, type: "QCM", enonce: "Chaque intervention sur les équipements spéciaux des taxis doit être consignée sur un carnet spécifique : comment s'appelle ce document ?", choix: [{ lettre: "A", texte: "carnet d'intervention spécifique" }, { lettre: "B", texte: "carnet métrologique", correct: true }, { lettre: "C", texte: "carnet d'entretien du véhicule" }] },
    { id: 14, type: "QCM", enonce: "Le financement en crédit-bail d'un véhicule de taxi permet la déduction fiscale :", choix: [{ lettre: "A", texte: "Des loyers du crédit-bail", correct: true }, { lettre: "B", texte: "De l'amortissement du véhicule" }, { lettre: "C", texte: "Des intérêts et de l'assurance décès/incapacité/invalidité" }] },
    { id: 15, type: "QCM", enonce: "Quelle(s) mention(s) ne doit(vent) pas figurer sur le registre des transactions quand le titulaire d'une ADS présente un successeur à titre onéreux ?", choix: [{ lettre: "A", texte: "le nom ou la raison sociale du successeur et du vendeur" }, { lettre: "B", texte: "le numéro d'inscription à la chambre des métiers", correct: true }, { lettre: "C", texte: "le montant de la transaction" }, { lettre: "D", texte: "la marque de la voiture", correct: true }] },
    { id: 16, type: "QCM", enonce: "Un transport vers l'hôpital non pris en charge par la caisse d'assurance maladie peut être effectué :", choix: [{ lettre: "A", texte: "uniquement par les taxis conventionnés" }, { lettre: "B", texte: "par tous les taxis", correct: true }, { lettre: "C", texte: "uniquement par les taxis non conventionnés" }] },
  ]
};

// =============================================
// EXAMEN BLANC 4 — TAXI — Réglementation locale (7 questions)
// =============================================
export const taxi_locale_eb4: Matiere = {
  id: "reglementation_taxi2",
  nom: "G(T) - Connaissance du territoire et réglementation locale TAXI",
  duree: 20, coefficient: 3, noteEliminatoire: 6, noteSur: 20,
  questions: [
    { id: 1, type: "QRC", enonce: "Quel est le tarif en vigueur d'horaire d'attente ou de marche lente dans le dernier arrêté préfectoral en vigueur ?", reponseQRC: "40,40 € soit une chute de 0,10 € toutes les 8,91 secondes.", reponses_possibles: ["40,40", "0,10", "8,91"] },
    { id: 2, type: "QRC", enonce: "Citez 4 ponts du Rhône.", reponseQRC: "Pont Raymond Barre. Pont Pasteur. Viaduc de Perrache. Pont Gallieni. Pont de l'Université. Pont de la Guillotière. Pont Wilson. Pont Lafayette. Pont Morand. Pont de Lattre-de-Tassigny. Pont Winston Churchill.", reponses_possibles: ["Raymond Barre", "Pasteur", "Perrache", "Gallieni", "Université", "Guillotière", "Wilson", "Lafayette", "Morand", "Lattre", "Churchill"] },
    { id: 3, type: "QCM", enonce: "Nous sommes le 24 décembre, il est 23h50. Un client souhaite effectuer un aller-retour de la gare Part-Dieu à la basilique de Notre-Dame de Fourvière. Quel tarif appliquez-vous ?", choix: [{ lettre: "A", texte: "Tarif A" }, { lettre: "B", texte: "Tarif B" }, { lettre: "C", texte: "Tarif C" }, { lettre: "D", texte: "Tarif D", correct: true }] },
    { id: 4, type: "QCM", enonce: "Les chauffeurs de taxi ont-ils le droit d'utiliser la même voie que les bus et les personnes effectuant du covoiturage sur la M6 et la M7 ?", choix: [{ lettre: "A", texte: "oui", correct: true }, { lettre: "B", texte: "non" }] },
    { id: 5, type: "QCM", enonce: "Quel cru ne fait pas partie de la vallée du Rhône ?", choix: [{ lettre: "A", texte: "Le crément", correct: true }, { lettre: "B", texte: "Le condrieu" }, { lettre: "C", texte: "Le Château Grillet" }, { lettre: "D", texte: "Le Saint-Joseph" }] },
    { id: 6, type: "QCM", enonce: "Y a-t-il un supplément pour les animaux ?", choix: [{ lettre: "A", texte: "Oui" }, { lettre: "B", texte: "Non", correct: true }] },
    { id: 7, type: "QCM", enonce: "Si vous souhaitez réaliser un « covering » publicitaire du véhicule TAXI, et que votre ADS est rattachée à Villeurbanne, à qui devrez-vous en faire la demande ?", choix: [{ lettre: "A", texte: "à la mairie de Villeurbanne" }, { lettre: "B", texte: "à la mairie de Villeurbanne et au Service en charge des Taxis à la Métropole de Lyon", correct: true }, { lettre: "C", texte: "au Service en charge des Taxis à la Métropole de Lyon", correct: true }] },
  ]
};

// =============================================
// EXAMEN BLANC 5 — TAXI — Réglementation nationale (15 questions)
// =============================================
export const taxi_nationale_eb5: Matiere = {
  id: "reglementation_taxi",
  nom: "F(T) - Réglementation nationale TAXI",
  duree: 30, coefficient: 3, noteEliminatoire: 6, noteSur: 20,
  questions: [
    { id: 1, type: "QRC", enonce: "Citez les trois éléments constitutifs du montant affiché sur le compteur horokilométrique.", reponseQRC: "La prise en charge, le tarif kilométrique et l'heure d'attente ou marche lente.", reponses_possibles: ["prise en charge", "tarif kilométrique", "heure d'attente", "marche lente"] },
    { id: 2, type: "QRC", enonce: "Lorsqu'un titulaire ne peut exploiter lui-même son autorisation de stationnement, quelles sont les deux possibilités qui s'offrent à lui pour que son entreprise reste active ?", reponseQRC: "La location du véhicule taxi à un conducteur de taxi. L'emploi d'un salarié.", reponses_possibles: ["location", "conducteur de taxi", "emploi", "salarié"] },
    { id: 3, type: "QRC", enonce: "Quelle est la définition du véhicule taxi ?", reponseQRC: "Le véhicule taxi est un véhicule automobile de catégorie M1, comportant outre le siège du conducteur huit places assises au maximum, ayant un PTAC ≤ 3,5 tonnes, muni d'équipements spéciaux, dont le propriétaire/exploitant est titulaire d'une ADS sur la voie publique en attente de la clientèle, afin d'effectuer à titre onéreux le transport public particulier de personnes et de leurs bagages.", reponses_possibles: ["M1", "huit places", "3,5 tonnes", "équipements spéciaux", "autorisation de stationnement", "voie publique", "titre onéreux"] },
    { id: 4, type: "QRC", enonce: "Quelle convention doit appliquer le taxi qui effectue un transport médical pour un assuré d'une CPAM différente de celle avec laquelle il a signé ?", reponseQRC: "Il doit appliquer la convention de la CPAM de son département.", reponses_possibles: ["convention", "CPAM", "département"] },
    { id: 5, type: "QCM", enonce: "Un conducteur de taxi peut-il transporter des colis non accompagnés ?", choix: [{ lettre: "A", texte: "oui, mais le conducteur se fait payer à l'arrivée par rapport au compteur" }, { lettre: "B", texte: "oui, à condition que le conducteur se fasse payer d'avance" }, { lettre: "C", texte: "non, c'est interdit car les taxis sont prévus pour le transport de personnes et de leurs bagages", correct: true }, { lettre: "D", texte: "non, même s'il a un contrat d'assistance bagages avec une compagnie aérienne" }] },
    { id: 6, type: "QCM", enonce: "Où doit-on adresser une demande de détaxe de carburants ?", choix: [{ lettre: "A", texte: "à la Direction des Douanes", correct: true }, { lettre: "B", texte: "à la Direction Départementale des Territoires et de la Mer" }, { lettre: "C", texte: "au bureau des taxis de la Préfecture" }] },
    { id: 7, type: "QCM", enonce: "Le conducteur de taxi a le droit :", choix: [{ lettre: "A", texte: "de ne pas attendre les voyageurs s'ils se trouvent dans une voie où le stationnement est impossible", correct: true }, { lettre: "B", texte: "de prendre en charge des voyageurs poursuivis par la clameur publique" }, { lettre: "C", texte: "d'être accompagné de personnes autres que des clients" }, { lettre: "D", texte: "de solliciter un pourboire" }] },
    { id: 8, type: "QCM", enonce: "Quelle est la prestation dont le conducteur de taxi artisan ne peut bénéficier ?", choix: [{ lettre: "A", texte: "la retraite de base" }, { lettre: "B", texte: "les allocations familiales" }, { lettre: "C", texte: "l'indemnité de chômage", correct: true }, { lettre: "D", texte: "l'indemnité journalière en maladie" }] },
    { id: 9, type: "QCM", enonce: "Les taxis sont des véhicules automobiles comportant :", choix: [{ lettre: "A", texte: "outre le siège du conducteur, 8 places assises au maximum", correct: true }, { lettre: "B", texte: "outre le siège du conducteur, 7 places assises au maximum" }, { lettre: "C", texte: "outre le siège du conducteur, 9 places assises au maximum" }, { lettre: "D", texte: "9 places assises y compris le siège du conducteur au maximum", correct: true }] },
    { id: 10, type: "QCM", enonce: "Qu'est-ce que le carnet de métrologie ?", choix: [{ lettre: "A", texte: "Un carnet de liaison entre l'installateur du matériel et le taxi", correct: true }, { lettre: "B", texte: "un cahier de note" }, { lettre: "C", texte: "un livre" }, { lettre: "D", texte: "Un certificat de conformité de l'installation du taximètre", correct: true }] },
    { id: 11, type: "QCM", enonce: "Nul ne peut s'inscrire à l'examen en vue de la délivrance du certificat de capacité professionnelle de conducteur de taxi :", choix: [{ lettre: "A", texte: "s'il a fait l'objet dans les 5 ans d'une exclusion pour fraude", correct: true }, { lettre: "B", texte: "s'il a fait l'objet dans les 10 ans d'une exclusion pour fraude" }, { lettre: "C", texte: "s'il a fait l'objet dans les 5 ans d'un retrait définitif de la carte professionnelle", correct: true }, { lettre: "D", texte: "s'il a fait l'objet dans les 10 ans d'un retrait définitif de la carte professionnelle", correct: true }] },
    { id: 12, type: "QCM", enonce: "Quel est le tarif maximum du prix de l'heure au niveau national ?", choix: [{ lettre: "A", texte: "40,15 €" }, { lettre: "B", texte: "41,15 €" }, { lettre: "C", texte: "42,15 €", correct: true }] },
    { id: 13, type: "QCM", enonce: "Quelle est l'autorité administrative compétente pour fixer localement une couleur unique des véhicules taxi ?", choix: [{ lettre: "A", texte: "Les présidents du tribunal de commerce" }, { lettre: "B", texte: "Les présidents de l'organisation professionnelle" }, { lettre: "C", texte: "Celle qui délivre les autorisations de stationnement", correct: true }, { lettre: "D", texte: "Les présidents de la chambre de métiers et de l'artisanat" }] },
    { id: 14, type: "QCM", enonce: "Lorsqu'il cesse d'exercer son activité, le titulaire de la carte professionnelle doit :", choix: [{ lettre: "A", texte: "la céder à titre onéreux" }, { lettre: "B", texte: "la détruire" }, { lettre: "C", texte: "la restituer à la préfecture qui l'a délivrée", correct: true }] },
    { id: 15, type: "QCM", enonce: "Lorsque le conducteur taxi est en service :", choix: [{ lettre: "A", texte: "Il peut éclairer le dispositif lumineux en vert s'il n'est pas occupé ou retenu" }, { lettre: "B", texte: "Il doit éclairer le dispositif lumineux en vert s'il n'est pas occupé ou retenu", correct: true }, { lettre: "C", texte: "Il a interdiction d'éclairer le dispositif lumineux en vert s'il n'est pas occupé ou retenu" }] },
  ]
};

// =============================================
// EXAMEN BLANC 5 — TAXI — Réglementation locale (8 questions)
// =============================================
export const taxi_locale_eb5: Matiere = {
  id: "reglementation_taxi2",
  nom: "G(T) - Connaissance du territoire et réglementation locale TAXI",
  duree: 20, coefficient: 3, noteEliminatoire: 6, noteSur: 20,
  questions: [
    { id: 1, type: "QRC", enonce: "Citez 4 boulevards du 8ème arrondissement de Lyon.", reponseQRC: "Boulevard Ambroise Paré. Boulevard Pinel. Boulevard des États-Unis. Boulevard Jean XXIII.", reponses_possibles: ["Ambroise Paré", "Pinel", "États-Unis", "Jean XXIII", "Jean 23"] },
    { id: 2, type: "QRC", enonce: "Citez 4 consulats du 2ème arrondissement de Lyon.", reponseQRC: "Consulat de Belgique. Consulat des Pays-Bas. Consulat des États-Unis. Consulat du Luxembourg. Consulat du Mexique. Consulat du Pérou. Consulat de Finlande. Consulat du Canada. Consulat de Thaïlande.", reponses_possibles: ["Belgique", "Pays-Bas", "États-Unis", "Luxembourg", "Mexique", "Pérou", "Finlande", "Canada", "Thaïlande"] },
    { id: 3, type: "QCM", enonce: "Quel nom est donné au principal monument religieux catholique sur Fourvière ?", choix: [{ lettre: "A", texte: "La cathédrale Saint-Jean" }, { lettre: "B", texte: "La basilique de Notre-Dame de Fourvière", correct: true }, { lettre: "C", texte: "L'église Saint-Georges" }, { lettre: "D", texte: "L'église Sainte-Blandine" }] },
    { id: 4, type: "QCM", enonce: "Le musée des Confluences est un musée :", choix: [{ lettre: "A", texte: "d'histoire naturelle, d'anthropologie, des sociétés et des civilisations", correct: true }, { lettre: "B", texte: "des beaux-arts" }, { lettre: "C", texte: "d'architecture romaine" }, { lettre: "D", texte: "d'art contemporain" }] },
    { id: 5, type: "QCM", enonce: "Quel évènement est célébré le 8 décembre à Lyon ?", choix: [{ lettre: "A", texte: "La galette des rois" }, { lettre: "B", texte: "La fête des lumières", correct: true }, { lettre: "C", texte: "La fête des marrons" }] },
    { id: 6, type: "QCM", enonce: "Où se trouve l'office du tourisme sur Lyon ?", choix: [{ lettre: "A", texte: "Place des Jacobins" }, { lettre: "B", texte: "Place Carnot" }, { lettre: "C", texte: "Place des Terreaux" }, { lettre: "D", texte: "Place Bellecour", correct: true }] },
    { id: 7, type: "QCM", enonce: "Quel nom portait la ville de Lyon à l'époque gallo-romaine ?", choix: [{ lettre: "A", texte: "Lyon By Night" }, { lettre: "B", texte: "Lugdunum", correct: true }, { lettre: "C", texte: "Lion" }, { lettre: "D", texte: "La gone" }] },
    { id: 8, type: "QCM", enonce: "Quel est le prix du tarif C ?", choix: [{ lettre: "A", texte: "1 €" }, { lettre: "B", texte: "2 €", correct: true }, { lettre: "C", texte: "3 €" }, { lettre: "D", texte: "4 €" }] },
  ]
};

// =============================================
// EXAMEN BLANC 6 — TAXI — Réglementation nationale (16 questions)
// =============================================
export const taxi_nationale_eb6: Matiere = {
  id: "reglementation_taxi",
  nom: "F(T) - Réglementation nationale TAXI",
  duree: 30, coefficient: 3, noteEliminatoire: 6, noteSur: 20,
  questions: [
    { id: 1, type: "QRC", enonce: "Comment appelle-t-on le document sur lequel sont consignées les opérations effectuées sur l'installation des équipements spéciaux des taxis ? Doit-il être en permanence dans le véhicule taxi ?", reponseQRC: "Carnet métrologique, oui il doit être en permanence dans le véhicule.", reponses_possibles: ["carnet métrologique", "permanence", "véhicule"] },
    { id: 2, type: "QRC", enonce: "Donner la définition de « taxi ».", reponseQRC: "Le véhicule taxi est un véhicule automobile de catégorie M1, comportant outre le siège du conducteur huit places assises au maximum, ayant un PTAC ≤ 3,5 tonnes, muni d'équipements spéciaux, dont le propriétaire/exploitant est titulaire d'une ADS sur la voie publique en attente de la clientèle, afin d'effectuer à titre onéreux le transport public particulier de personnes et de leurs bagages.", reponses_possibles: ["M1", "huit places", "3,5 tonnes", "équipements spéciaux", "autorisation de stationnement", "voie publique", "titre onéreux"] },
    { id: 3, type: "QRC", enonce: "Lors du transfert des ADS, quel délai a le nouveau titulaire pour déclarer la transaction à la recette des impôts compétente, à partir de la date de conclusion ?", reponseQRC: "1 mois.", reponses_possibles: ["1 mois", "un mois"] },
    { id: 4, type: "QRC", enonce: "Quelles sont les deux fonctions du compteur horokilométrique ?", reponseQRC: "Fonction horaire. Fonction kilométrique.", reponses_possibles: ["horaire", "kilométrique"] },
    { id: 5, type: "QCM", enonce: "Titulaire d'une ADS, suite à une blessure, puis-je demander à une connaissance titulaire de la carte professionnelle d'un autre département de conduire mon taxi ?", choix: [{ lettre: "A", texte: "non", correct: true }, { lettre: "B", texte: "oui mais seulement pendant 10 jours" }, { lettre: "C", texte: "oui, sous conditions" }] },
    { id: 6, type: "QCM", enonce: "Quelle(s) mention(s) figure(nt) sur la liste d'attente des délivrances des ADS ?", choix: [{ lettre: "A", texte: "Numéro d'enregistrement de la demande", correct: true }, { lettre: "B", texte: "Numéro de la carte professionnelle" }, { lettre: "C", texte: "Date de dépôt de la demande", correct: true }, { lettre: "D", texte: "État civil du demandeur", correct: true }] },
    { id: 7, type: "QCM", enonce: "Sur quelle base la consommation de mon carburant professionnel est-elle remboursée ?", choix: [{ lettre: "A", texte: "Sur la base du prix TTC payé à la pompe" }, { lettre: "B", texte: "Sur la base d'un forfait kilométrique" }, { lettre: "C", texte: "Sur la base du nombre de litres consommés dans la limite d'un contingent annuel", correct: true }] },
    { id: 8, type: "QCM", enonce: "De quel régime de sécurité sociale dépend le locataire-gérant ?", choix: [{ lettre: "A", texte: "Régime autonome des professions indépendantes non agricoles" }, { lettre: "B", texte: "Régime agricole" }, { lettre: "C", texte: "Régime général", correct: true }, { lettre: "D", texte: "Régimes spéciaux" }] },
    { id: 9, type: "QCM", enonce: "Quelles sont les conditions pour être artisan taxi ?", choix: [{ lettre: "A", texte: "Être inscrit sur une liste d'attente d'une ADS" }, { lettre: "B", texte: "Être répertorié à l'INSEE", correct: true }, { lettre: "C", texte: "Être titulaire d'une ou plusieurs ADS", correct: true }] },
    { id: 10, type: "QCM", enonce: "Lorsqu'il est en service, le conducteur taxi peut :", choix: [{ lettre: "A", texte: "Solliciter un client par le geste ou la parole dans une station taxi" }, { lettre: "B", texte: "Solliciter un pourboire" }, { lettre: "C", texte: "Prendre en charge un client en dehors de son ressort géographique s'il justifie d'une réservation préalable", correct: true }, { lettre: "D", texte: "Refuser une destination en dehors du ressort géographique de l'ADS" }] },
    { id: 11, type: "QCM", enonce: "Parmi ces affirmations, laquelle est vraie ?", choix: [{ lettre: "A", texte: "La carte professionnelle est délivrée par le Préfet ou le Préfet de Police", correct: true }, { lettre: "B", texte: "La carte professionnelle mentionne les départements dans lesquels on est autorisé à exercer" }, { lettre: "C", texte: "La carte professionnelle mentionne la commune dans laquelle on est autorisé à exercer" }, { lettre: "D", texte: "La carte professionnelle est délivrée par la Mairie" }] },
    { id: 12, type: "QCM", enonce: "À qui est adressée la taxe de stationnement ?", choix: [{ lettre: "A", texte: "Au Préfet/Préfet de Police" }, { lettre: "B", texte: "Au ministre de l'intérieur" }, { lettre: "C", texte: "Au Maire", correct: true }] },
    { id: 13, type: "QCM", enonce: "L'autorisation de stationnement délivrée à titre gratuit postérieurement à la loi n°2014-1104 du 1er octobre 2014 :", choix: [{ lettre: "A", texte: "est renouvelable dans des conditions fixées par décret", correct: true }, { lettre: "B", texte: "a une durée de validité de 5 ans", correct: true }, { lettre: "C", texte: "est cessible à titre onéreux" }] },
    { id: 14, type: "QCM", enonce: "Quel est le service compétent pour conventionner un conducteur de taxi au TAP ?", choix: [{ lettre: "A", texte: "La Mairie dont dépend l'ADS" }, { lettre: "B", texte: "La CPAM départementale dont dépend l'ADS", correct: true }, { lettre: "C", texte: "La Préfecture du département" }, { lettre: "D", texte: "L'Agence Régionale de Santé" }] },
    { id: 15, type: "QCM", enonce: "Le véhicule taxi doit être muni d'une plaque de stationnement :", choix: [{ lettre: "A", texte: "sur le toit du véhicule" }, { lettre: "B", texte: "fixée au véhicule", correct: true }, { lettre: "C", texte: "indiquant le nom de la commune de rattachement" }, { lettre: "D", texte: "collée au véhicule" }] },
    { id: 16, type: "QCM", enonce: "Le conducteur de taxi a le droit :", choix: [{ lettre: "A", texte: "d'être accompagné de personnes autres que des clients" }, { lettre: "B", texte: "de solliciter un pourboire" }, { lettre: "C", texte: "de ne pas attendre les voyageurs s'ils se trouvent dans une voie où le stationnement est impossible", correct: true }, { lettre: "D", texte: "de prendre en charge des voyageurs poursuivis par la clameur publique" }] },
  ]
};

// =============================================
// EXAMEN BLANC 6 — TAXI — Réglementation locale (8 questions)
// =============================================
export const taxi_locale_eb6: Matiere = {
  id: "reglementation_taxi2",
  nom: "G(T) - Connaissance du territoire et réglementation locale TAXI",
  duree: 20, coefficient: 3, noteEliminatoire: 6, noteSur: 20,
  questions: [
    { id: 1, type: "QRC", enonce: "Le 24 décembre 2022 à 7h05, vous êtes en attente client à la station de Taxi de l'aéroport Lyon Saint-Exupéry quand 5 jeunes vous sollicitent pour les amener à l'hôtel Sofitel situé quai Gailleton à Lyon 2ème. Ces clients ont 15 bagages au total et votre véhicule est suffisamment volumineux. Calculez le montant de la prise en charge.", reponseQRC: "Prise en charge = 3 € + supplément passagers (4 passagers supplémentaires × 4 € = 16 €) + supplément bagages.", reponses_possibles: ["prise en charge", "supplément", "passagers", "bagages"], requiresCalcul: true },
    { id: 2, type: "QRC", enonce: "Quelle est la définition et le prix au km des tarifs B et C ?", reponseQRC: "Tarif B : retour à vide de jour = 1,50 €/km. Tarif C : course de nuit, dimanche, jours fériés = 2 €/km.", reponses_possibles: ["retour à vide", "1,50", "nuit", "dimanche", "2"] },
    { id: 3, type: "QCM", enonce: "Selon la réglementation en vigueur sur la métropole de Lyon, parmi ces situations, lesquelles ne permettent pas d'affecter un véhicule à l'activité de Taxi ?", choix: [{ lettre: "A", texte: "Véhicule de plus de 13 ans", correct: true }, { lettre: "B", texte: "Véhicule de couleur rouge" }, { lettre: "C", texte: "Véhicule mis en service il y a 8 ans pour la première fois", correct: true }] },
    { id: 4, type: "QCM", enonce: "Parmi ces personnalités, lesquelles sont originaires de Lyon ?", choix: [{ lettre: "A", texte: "Jean Dujardin" }, { lettre: "B", texte: "Bertrand Tavernier", correct: true }, { lettre: "C", texte: "Claude Lelouch" }, { lettre: "D", texte: "Florence Foresti", correct: true }] },
    { id: 5, type: "QCM", enonce: "Selon l'arrêté métropolitain de réglementation des Taxis, quel est le volume minimum du coffre accordé pour un véhicule thermique ?", choix: [{ lettre: "A", texte: "400 litres", correct: true }, { lettre: "B", texte: "500 litres" }, { lettre: "C", texte: "600 litres" }, { lettre: "D", texte: "700 litres" }] },
    { id: 6, type: "QCM", enonce: "Selon l'arrêté préfectoral de réglementation des Taxis, quel est le nombre de communes qui intègre la ZUPC (zone unique de prise en charge) ?", choix: [{ lettre: "A", texte: "15 communes" }, { lettre: "B", texte: "20 communes" }, { lettre: "C", texte: "24 communes", correct: true }, { lettre: "D", texte: "26 communes" }] },
    { id: 7, type: "QCM", enonce: "Au départ de la place Bellecour à Lyon, quels axes autoroutier et/ou périphérique allez-vous emprunter pour rejoindre Clermont-Ferrand ?", choix: [{ lettre: "A", texte: "A7" }, { lettre: "B", texte: "M6", correct: true }, { lettre: "C", texte: "A89", correct: true }, { lettre: "D", texte: "A46" }] },
    { id: 8, type: "QCM", enonce: "Vous êtes titulaire d'une ADS de Vénissieux et vous souhaitez apposer une publicité sur la carrosserie de votre véhicule. Quelle(s) autorisation(s) devez-vous obtenir ?", choix: [{ lettre: "A", texte: "Autorisation du préfet" }, { lettre: "B", texte: "Autorisation du service en charge des taxis de la Métropole", correct: true }, { lettre: "C", texte: "Autorisation de la direction départementale de la protection des populations" }] },
  ]
};
