import type { Slide } from "./t3p-partie1-data";
import consulatsImg from "@/assets/ville/consulats.jpg";

export const VILLE_CONSULATS_SLIDES: Slide[] = [
  {
    type: "title",
    title: "Les Consulats",
    subtitle: "Consulats et représentations diplomatiques à Lyon",
    footer: "Connaissances de la ville — Module 7",
    brand: "FTRANSPORT",
    image: consulatsImg,
  },
  {
    type: "content",
    title: "🏛️ Consulats — Partie 1",
    blocks: [
      { heading: "1. Consulat de Pologne", color: "#ef4444", points: ["📍 79 Rue Crillon, 69006 Lyon"] },
      { heading: "2. Consulat du Portugal", color: "#10b981", points: ["📍 71 Rue Crillon, 69006 Lyon"] },
      { heading: "3. Consulat d'Algérie", color: "#f59e0b", points: ["📍 126 Rue Vauban, 69006 Lyon"] },
      { heading: "4. Consulat du Sénégal", color: "#8b5cf6", points: ["📍 97 Rue Garibaldi, 69006 Lyon"] },
    ],
  },
  {
    type: "content",
    title: "🏛️ Consulats — Partie 2",
    blocks: [
      { heading: "5. Consulat de Chine", color: "#06b6d4", points: ["📍 69 Rue Duquesne, 69006 Lyon"] },
      { heading: "6. Consulat d'Espagne", color: "#ec4899", points: ["📍 1 Rue Louis Guérin, 69100 Villeurbanne"] },
      { heading: "7. Consulat du Maroc", color: "#ef4444", points: ["📍 2/4 Rue Carry, 69003 Lyon"] },
      { heading: "8. Consulat de Slovaquie", color: "#f59e0b", points: ["📍 121 Cours du Docteur Long, 69003 Lyon"] },
    ],
  },
  {
    type: "content",
    title: "🏛️ Consulats — Partie 3",
    blocks: [
      { heading: "9. Consulat de Tunisie", color: "#10b981", points: ["📍 14 Avenue Maréchal Foch, 69006 Lyon"] },
      { heading: "10. Consulat d'Allemagne", color: "#8b5cf6", points: ["📍 33 Boulevard des Belges, 69006 Lyon"] },
      { heading: "11. Consulat des États-Unis", color: "#3b82f6", points: ["📍 1 Quai Jules Courmont, 69002 Lyon"] },
      { heading: "12. Consulat d'Arménie", color: "#ec4899", points: ["📍 2 Passage Feuillat, 69003 Lyon"] },
    ],
  },
  {
    type: "content",
    title: "🏛️ Consulats — Partie 4",
    blocks: [
      { heading: "13. Consulat de Suisse", color: "#ef4444", points: ["📍 4 Place Charles Hernu, 69100 Villeurbanne"] },
      { heading: "14. Consulat de Belgique", color: "#f59e0b", points: ["📍 8 Rue de la République, 69002 Lyon"] },
      { heading: "15. Consulat de Norvège", color: "#06b6d4", points: ["📍 3 Rue Dumont, 69004 Lyon"] },
      { heading: "16. Consulat du Luxembourg", color: "#10b981", points: ["📍 6 Rue Grolée, 69002 Lyon"] },
    ],
  },
  {
    type: "content",
    title: "🏛️ Consulats — Partie 5",
    blocks: [
      { heading: "17. Consulat du Mexique", color: "#8b5cf6", points: ["📍 6 Place Bellecour, 69002 Lyon"] },
      { heading: "18. Consulat du Pérou", color: "#ec4899", points: ["📍 3 Place de la Bourse, 69002 Lyon"] },
      { heading: "19. Consulat de Roumanie", color: "#ef4444", points: ["📍 29 Rue de Bonnel, 69003 Lyon"] },
      { heading: "20. Consulat de Finlande", color: "#f59e0b", points: ["📍 3 Rue de la Barre, 69002 Lyon"] },
    ],
  },
  {
    type: "content",
    title: "🏛️ Consulats — Partie 6",
    blocks: [
      { heading: "21. Consulat du Canada", color: "#10b981", points: ["📍 3 Place de la Bourse, 69002 Lyon"] },
      { heading: "22. Consulat de Côte d'Ivoire", color: "#06b6d4", points: ["📍 58 Avenue Maréchal Foch, 69006 Lyon"] },
      { heading: "23. Consulat de Malte", color: "#8b5cf6", points: ["📍 15 Place Jules Ferry, 69006 Lyon"] },
      { heading: "24. Consulat de Russie (fermé)", color: "#ec4899", points: ["📍 55 Rue du Sergent Michel Berthet, 69009 Lyon", "⚠️ Ce consulat n'est plus en activité à Lyon"] },
    ],
  },
  {
    type: "content",
    title: "🏛️ Consulats — Partie 7",
    blocks: [
      { heading: "25. Consulat de Suède", color: "#ef4444", points: ["📍 107 Rue Servient, 69003 Lyon"] },
      { heading: "26. Consulat du Danemark", color: "#f59e0b", points: ["📍 136 Cours Lafayette, 69003 Lyon"] },
      { heading: "27. Consulat d'Italie", color: "#10b981", points: ["📍 5 Rue du Commandant Faurax, 69006 Lyon"] },
      { heading: "28. Consulat d'Irlande", color: "#06b6d4", points: ["📍 158 Avenue Roger Salengro, 69100 Villeurbanne"] },
      { heading: "29. Consulat du Japon", color: "#8b5cf6", points: ["📍 131 Boulevard de Stalingrad, 69100 Villeurbanne"] },
    ],
  },
  {
    type: "table",
    title: "📋 Récapitulatif — Les Consulats",
    headers: ["Pays", "Adresse"],
    rows: [
      ["Pologne", "79 Rue Crillon, 69006"],
      ["Portugal", "71 Rue Crillon, 69006"],
      ["Algérie", "126 Rue Vauban, 69006"],
      ["Sénégal", "97 Rue Garibaldi, 69006"],
      ["Chine", "69 Rue Duquesne, 69006"],
      ["Espagne", "1 Rue L. Guérin, 69100"],
      ["Maroc", "2/4 Rue Carry, 69003"],
      ["Slovaquie", "121 Cours Dr Long, 69003"],
      ["Tunisie", "14 Av. M. Foch, 69006"],
      ["Allemagne", "33 Bd des Belges, 69006"],
      ["États-Unis", "1 Quai J. Courmont, 69002"],
      ["Arménie", "2 Passage Feuillat, 69003"],
      ["Suisse", "4 Pl. C. Hernu, 69100"],
      ["Belgique", "8 Rue République, 69002"],
      ["Norvège", "3 Rue Dumont, 69004"],
      ["Luxembourg", "6 Rue Grolée, 69002"],
      ["Mexique", "6 Pl. Bellecour, 69002"],
      ["Pérou", "3 Pl. de la Bourse, 69002"],
      ["Roumanie", "29 Rue Bonnel, 69003"],
      ["Finlande", "3 Rue de la Barre, 69002"],
      ["Canada", "3 Pl. de la Bourse, 69002"],
      ["Côte d'Ivoire", "58 Av. M. Foch, 69006"],
      ["Malte", "15 Pl. Jules Ferry, 69006"],
      ["Russie", "55 Rue S.M. Berthet, 69009"],
      ["Suède", "107 Rue Servient, 69003"],
      ["Danemark", "136 Cours Lafayette, 69003"],
      ["Italie", "5 Rue Cdt Faurax, 69006"],
      ["Irlande", "158 Av. R. Salengro, 69100"],
      ["Japon", "131 Bd Stalingrad, 69100"],
    ],
  },
];
