INSERT INTO public.email_templates (id, label, icon, subject_template, body_template)
VALUES 
(
  'felicitations-taxi',
  '🎉 Félicitations TAXI',
  '🎉',
  'Félicitations {{prenom}} ! Vous êtes maintenant chauffeur TAXI',
  'Bonjour {{prenom}},<br><br>Félicitations, vous êtes maintenant chauffeur TAXI, nous tenions encore une fois à vous féliciter et à vous remercier pour votre persévérance, votre patiente et de toute la confiance que vous nous avez accordée.<br><br>Il faudra maintenant attendre l''attestation de réussite que vous enverra la chambre des métiers et de l''artisanat par voie postale, et demander votre carte professionnelle en cliquant sur le lien suivant :<br><br><a href="https://www.demarches-simplifiees.fr/commencer/demande-carte-professionnelle-de-conducteur-de-t">Cliquez ICI pour demander votre carte TAXI</a><br><br><strong>Attention</strong>, vous devez demander votre carte Taxi sur le département du Rhône, même si vous résidez dans un autre département que le 69.<br><br>Votre carte professionnelle est rattachée au département où vous passez l''examen.<br>Elle n''est valide que pour exercer votre activité dans ce département.<br><br><strong>Attention</strong>, avant d''effectuer votre demande de carte professionnelle, vous devez obtenir un rendez-vous auprès d''un médecin agréé conduite pour l''obtention d''un certificat médical et passer une formation PSC1.<br><br><a href="https://www.croix-rouge.fr/je-me-forme/particuliers/premiers-secours">Cliquez ici pour choisir une date pour la formation PSC1 Croix Rouge</a><br><br><a href="https://www.protection-civile.org/psc1">Cliquez ici pour choisir une date pour la formation PSC1 Protection Civile</a><br><br>Vous trouverez en pièce jointe la liste des médecins agréés conduite.<br><br>Vous devez également répondre au mail envoyé par l''imprimerie nationale en envoyant une photo et une signature depuis votre téléphone portable ou ordinateur de bureau.<br><br>N''oubliez pas aussi de faire tamponner votre certificat médical après réception de la carte professionnelle.<br><br>Nous vous serions très reconnaissants de laisser un avis Google sur notre page afin de partager votre expérience au centre de formation.<br><br><a href="https://g.page/r/ftransport/review">Cliquez ICI pour laisser un avis sur le centre</a><br><br>Pour l''achat ou la location d''une licence n''hésitez pas à vous renseigner auprès de :<br>- Le Bon Coin<br>- Mingat Vaulx en Velin<br>- Taxi Lyonnais<br>- Allo Taxi Genas<br><br>Sachez que nous pouvons vous aider pour l''attribution de la carte professionnelle. Pour cela il faudra nous contacter.<br><br>Nous vous souhaitons un excellent début d''aventure !!!<br><br>Cordialement,<br>FTRANSPORT'
),
(
  'felicitations-vtc',
  '🎉 Félicitations VTC',
  '🎉',
  'Félicitations {{prenom}} ! Vous êtes maintenant chauffeur VTC',
  'Bonjour {{prenom}},<br><br>Félicitations, vous êtes maintenant chauffeur VTC, nous tenions encore une fois à vous féliciter et à vous remercier pour votre persévérance, votre patiente et de toute la confiance que vous nous avez accordée.<br><br>Il faudra maintenant attendre l''attestation de réussite que vous enverra la chambre des métiers et de l''artisanat par voie postale, et demander votre carte professionnelle en cliquant sur le lien suivant :<br><br><a href="https://www.demarches-simplifiees.fr/commencer/demande-carte-vtc-rhone">Cliquez ICI pour demander votre carte VTC si vous habitez dans le Rhône</a><br><br><a href="https://www.demarches-simplifiees.fr/commencer/demande-carte-vtc-isere">Cliquez ICI pour demander votre carte VTC si vous habitez dans l''Isère</a><br><br><a href="https://www.demarches-simplifiees.fr/commencer/demande-carte-vtc-loire">Cliquez ICI pour demander votre carte VTC si vous habitez dans la Loire</a><br><br><a href="https://www.demarches-simplifiees.fr/commencer/demande-carte-vtc-haute-savoie">Cliquez ICI pour demander votre carte VTC si vous habitez en Haute-Savoie</a><br><br><strong>Attention</strong>, cela concerne uniquement les personnes qui résident dans le Rhône. Les autres devront contacter la préfecture de leur département.<br><br><strong>Attention</strong>, avant d''effectuer votre demande de carte professionnelle, vous devez obtenir un rendez-vous auprès d''un médecin agréé conduite pour l''obtention d''un certificat médical.<br><br>Vous trouverez en pièce jointe la liste des médecins agréés conduite.<br><br>Vous devez également répondre au mail envoyé par l''imprimerie nationale en envoyant une photo et une signature depuis votre téléphone portable ou ordinateur de bureau.<br><br>N''oubliez pas aussi de faire tamponner votre certificat médical après réception de la carte professionnelle.<br><br>Nous vous serions très reconnaissants de laisser un avis Google sur notre page afin de partager votre expérience au centre de formation.<br><br><a href="https://g.page/r/ftransport/review">Cliquez ICI pour laisser un avis sur le centre</a><br><br>Sachez que nous pouvons vous aider pour l''obtention de la carte professionnelle, pour cela, il faudra nous contacter.<br><br>Nous vous souhaitons prospérité et bonheur dans votre nouvelle activité.<br><br>Si vous trouvez des difficultés à demander votre carte professionnelle, nous pouvons le faire à votre place, nous procédons aussi à l''inscription au registre des VTC, le tout pour 30 euros, pour cela, contactez-nous directement par téléphone.<br><br>Cordialement,<br>FTRANSPORT'
);